import ClientProviders from "../../components/ClientProvider";
import "./globals.css";

export const metadata = {
  title: 'RetroVibe',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
